# CARLA Data Collection & Calibration (Reordered Notebook)

This notebook is a cleaned-up, logically ordered version of your original `CARLA.ipynb`. All original code cells are preserved; only their order has been rearranged and a few markdown section headers have been added for clarity.


## 1. Environment & Virtualenv Setup (Windows)
These cells create and configure the `carla-env` virtual environment and install CARLA.


In [2]:
!python -m venv carla-env


In [6]:
!carla-env\\Scripts\\python.exe -m pip install --upgrade pip
!carla-env\\Scripts\\python.exe -m pip install ipykernel


   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 1.8/1.8 MB 13.8 MB/s eta 0:00:00
  Attempting uninstall: pip
    Found existing installation: pip 24.2
    Uninstalling pip-24.2:
      Successfully uninstalled pip-24.2
   ---------------------------------------- 0.0/5.3 MB ? eta -:--:--
   ---------------------------------------- 5.3/5.3 MB 24.9 MB/s  0:00:00
   ---------------------------------------- 0.0/616.2 kB ? eta -:--:--
   ---------------------------------------- 616.2/616.2 kB 22.1 MB/s  0:00:00
   ---------------------------------------- 0.0/1.6 MB ? eta -:--:--
   ---------------------------------------- 1.6/1.6 MB 27.9 MB/s  0:00:00
   ---------------------------------------- 0.0/1.2 MB ? eta -:--:--
   ---------------------------------------- 1.2/1.2 MB 31.1 MB/s  0:00:00
   ---------------------------------------- 0.0/619.5 kB ? eta -:--:--
   ---------------------------------------- 619.5/619.5 kB 11.5 MB/s

In [8]:
!carla-env\\Scripts\\python.exe -m ipykernel install --user --name=carla-env --display-name "Python (carla-env)"


Installed kernelspec carla-env in C:\Users\avant\AppData\Roaming\jupyter\kernels\carla-env


In [7]:
!pip install carla==0.9.16


In [28]:
############### AFTER DOWNLOADING AND XTRACTING THE CARLA
!C:\Users\avant\carla-env\Scripts\python.exe -m pip install --upgrade pip
# verify the wheel file exists (adjust the path if you put CARLA elsewhere)
!dir "C:\CARLA_0.9.16\PythonAPI\carla\dist"

# install the exact wheel (cp312 matches Python 3.12; if you're on 3.10 it would be cp310)
!C:\Users\avant\carla-env\Scripts\pip.exe install "C:\CARLA_0.9.16\PythonAPI\carla\dist\carla-0.9.16-cp312-cp312-win_amd64.whl"


The system cannot find the path specified.


Processing c:\carla_0.9.16\pythonapi\carla\dist\carla-0.9.16-cp312-cp312-win_amd64.whl


ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: 'C:\\CARLA_0.9.16\\PythonAPI\\carla\\dist\\carla-0.9.16-cp312-cp312-win_amd64.whl'



In [36]:
!dir "C:\Users\avant\Downloads\CARLA_0.9.16"
!dir "C:\Users\avant\Downloads\CARLA_0.9.16\WindowsNoEditor"

 Volume in drive C is Windows
 Volume Serial Number is CE76-E195

 Directory of C:\Users\avant\Downloads\CARLA_0.9.16

04-11-2025  11:38    <DIR>          .
04-11-2025  11:34    <DIR>          ..
04-11-2025  11:38    <DIR>          CarlaUE4
15-09-2025  21:31           191,488 CarlaUE4.exe
08-09-2025  17:50            74,725 CHANGELOG
04-11-2025  11:38    <DIR>          Co-Simulation
10-09-2025  17:45               821 Dockerfile
04-11-2025  11:38    <DIR>          Engine
04-11-2025  11:38    <DIR>          HDMaps
23-06-2025  09:17             1,155 LICENSE
04-11-2025  11:38    <DIR>          PythonAPI
23-06-2025  09:17             1,651 README
               5 File(s)        269,840 bytes
               7 Dir(s)  608,008,937,472 bytes free
 Volume in drive C is Windows
 Volume Serial Number is CE76-E195

 Directory of C:\Users\avant\Downloads\CARLA_0.9.16



File Not Found


In [38]:
!dir "C:\Users\avant\Downloads\CARLA_0.9.16\PythonAPI\carla\dist"


 Volume in drive C is Windows
 Volume Serial Number is CE76-E195

 Directory of C:\Users\avant\Downloads\CARLA_0.9.16\PythonAPI\carla\dist

04-11-2025  11:38    <DIR>          .
04-11-2025  11:38    <DIR>          ..
15-09-2025  21:13         5,037,187 carla-0.9.16-cp312-cp312-win_amd64.whl
               1 File(s)      5,037,187 bytes
               2 Dir(s)  607,922,475,008 bytes free


In [40]:
!C:\Users\avant\carla-env\Scripts\pip.exe install "C:\Users\avant\Downloads\CARLA_0.9.16\PythonAPI\carla\dist\carla-0.9.16-cp312-cp312-win_amd64.whl"


Processing c:\users\avant\downloads\carla_0.9.16\pythonapi\carla\dist\carla-0.9.16-cp312-cp312-win_amd64.whl
carla is already installed with the same version as the provided wheel. Use --force-reinstall to force an installation of the wheel.


## 2. Basic Imports & Sanity Checks
Quick imports and sanity checks that CARLA can be imported.


In [1]:
import sys
print(sys.executable)


C:\Users\avant\carla-env\Scripts\python.exe


In [26]:
import sys, carla
print(sys.executable)
print("carla module:", carla.__file__)


C:\Users\avant\carla-env\Scripts\python.exe
carla module: C:\Users\avant\carla-env\Lib\site-packages\carla\__init__.py


## 3. Connect to CARLA and Single-Camera Demo
Connect to the CARLA server, spawn an ego vehicle, attach a single RGB camera, and capture a few frames.


In [1]:
import carla
client = carla.Client("127.0.0.1", 2000)
client.set_timeout(20.0)

world = client.get_world()
print("Connected to map:", world.get_map().name)


Connected to map: Carla/Maps/Town10HD_Opt


In [3]:
from pathlib import Path
import time

bp = world.get_blueprint_library()
vehicle_bp = bp.filter('vehicle.tesla.model3')[0]
spawn = world.get_map().get_spawn_points()[0]
ego = world.try_spawn_actor(vehicle_bp, spawn)
assert ego is not None, "Failed to spawn vehicle."
ego.set_autopilot(True)

Path("images").mkdir(exist_ok=True)

cam_bp = bp.find('sensor.camera.rgb')
cam_bp.set_attribute('image_size_x', '1280')
cam_bp.set_attribute('image_size_y', '720')
cam_bp.set_attribute('fov', '90')

cam_tf = carla.Transform(carla.Location(x=1.6, z=1.5), carla.Rotation(yaw=0))
cam = world.spawn_actor(cam_bp, cam_tf, attach_to=ego)

def save_img(image):
    image.save_to_disk('images/frame_%06d.jpg' % image.frame)

cam.listen(save_img)
print("Capturing frames for ~10 seconds...")
time.sleep(10)


Capturing frames for ~10 seconds...


In [4]:
cam.stop()
cam.destroy()
ego.destroy()
print("Cleanup done.")


Cleanup done.


## 4. Multi-Camera Rig (6 Cameras) with Sync Mode
Set up an ego vehicle in autopilot, enable synchronous mode, define a 6-camera rig, record synchronized images, and clean up.


In [5]:
import carla
from pathlib import Path

# blueprint library
bp_lib = world.get_blueprint_library()
vehicle_bp = bp_lib.filter('vehicle.tesla.model3')[0]

# spawn point
spawn_point = world.get_map().get_spawn_points()[0]
ego = world.try_spawn_actor(vehicle_bp, spawn_point)
assert ego is not None, "Failed to spawn ego vehicle."
ego.set_autopilot(True)  # makes it drive automatically

print("✅ Spawned ego vehicle:", ego.id)


✅ Spawned ego vehicle: 26


In [11]:
# Enable sync mode so all sensors tick together
####go synchronous (better alignment)
settings = world.get_settings()
settings.synchronous_mode = True
settings.fixed_delta_seconds = 0.1  # 10 Hz
world.apply_settings(settings)
print("Synchronous mode ON @ 10 Hz")


Synchronous mode ON @ 10 Hz


In [13]:
from pathlib import Path
import os, math, time

# Where to save
root = Path("multi_images")
scene = "scene_0002"
env   = "rainy"          # change per weather: clear/rain/fog/night
base  = root / env / scene
base.mkdir(parents=True, exist_ok=True)

# Camera layout (relative to ego vehicle)
CAM_RIG = {
    "CAM_FRONT":       dict(x=1.6,  y=0.0,  z=1.5, yaw=0),
    "CAM_FRONT_RIGHT": dict(x=1.4,  y=0.4,  z=1.5, yaw=45),
    "CAM_FRONT_LEFT":  dict(x=1.4,  y=-0.4, z=1.5, yaw=-45),
    "CAM_BACK":        dict(x=-1.5, y=0.0,  z=1.5, yaw=180),
    "CAM_LEFT":        dict(x=0.0,  y=-0.6, z=1.5, yaw=-90),
    "CAM_RIGHT":       dict(x=0.0,  y=0.6,  z=1.5, yaw=90),
}

# Image settings
W, H = 1280, 720
HFOV_DEG = 90.0

# One folder per camera
for name in CAM_RIG:
    (base / name).mkdir(parents=True, exist_ok=True)

print("Saving to:", base)


Saving to: multi_images\rainy\scene_0002


In [15]:
# Build the camera blueprint
cam_bp = bp_lib.find('sensor.camera.rgb')
cam_bp.set_attribute('image_size_x', str(W))
cam_bp.set_attribute('image_size_y', str(H))
cam_bp.set_attribute('fov', str(HFOV_DEG))

# Spawn + attach
cams = {}
for name, spec in CAM_RIG.items():
    tf = carla.Transform(
        carla.Location(x=spec['x'], y=spec['y'], z=spec['z']),
        carla.Rotation(pitch=0.0, roll=0.0, yaw=spec['yaw'])
    )
    cams[name] = world.spawn_actor(cam_bp, tf, attach_to=ego)

# Simple listeners that save with timestamp (microseconds) so frames line up
listeners = []
def make_listener(name):
    out_dir = base / name
    def _cb(image):
        ts_us = int(image.timestamp * 1e6)
        image.save_to_disk(str(out_dir / f"{ts_us:016d}.jpg"))
    return _cb

for name, cam in cams.items():
    cb = make_listener(name)
    cam.listen(cb)
    listeners.append((cam, cb))

print(f"Spawned and listening on {len(cams)} cameras:", list(cams.keys()))


Spawned and listening on 6 cameras: ['CAM_FRONT', 'CAM_FRONT_RIGHT', 'CAM_FRONT_LEFT', 'CAM_BACK', 'CAM_LEFT', 'CAM_RIGHT']


In [17]:
N_SECONDS = 10  # how long to record
ticks = int(N_SECONDS / world.get_settings().fixed_delta_seconds)

print(f"Capturing {N_SECONDS}s …")
for _ in range(ticks):
    world.tick()   # advances all sensors in sync

print("Done. Check:", base)


Capturing 10s …
Done. Check: multi_images\rainy\scene_0002


In [18]:
for cam, _ in listeners:
    try:
        cam.stop()
    except:
        pass
    cam.destroy()

# (Optional) return to async mode
s = world.get_settings()
s.synchronous_mode = False
s.fixed_delta_seconds = None
world.apply_settings(s)
print("Cameras destroyed. Synchronous mode OFF.")


Cameras destroyed. Synchronous mode OFF.


## 5. Weather Presets & Camera Tuning Utilities
Helper functions and snippets to configure snow/fog/rain presets and cool down camera exposure/white balance.


In [19]:
import carla

def set_weather_snow(world, variant="day"):
    """
    Approximate snowy conditions:
      - heavy cloud cover
      - strong fog (reduced visibility)
      - low sun (flat lighting)
      - zero rain/wetness (keep road dry unless you want slush)
    variant: "day" or "night"
    """
    w = world.get_weather()
    w.cloudiness = 100.0
    w.precipitation = 0.0               # CARLA rain looks like rain, not snow
    w.precipitation_deposits = 0.0
    w.wetness = 0.0                      # set >0 if you want “wet winter” roads
    w.wind_intensity = 60.0

    # fog → key for snowy visibility
    w.fog_density = 80.0
    w.fog_distance = 20.0               # lower = thicker fog near camera
    w.fog_falloff = 2.0

    # cold/flat light
    w.sun_azimuth_angle = 45.0
    w.sun_altitude_angle = 5.0 if variant == "day" else -10.0

    # optional scattering tweaks (if available in your build)
    try:
        w.scattering_intensity = 0.2
        w.mie_scattering_scale = 0.03
        w.rayleigh_scattering_scale = 0.2
    except Exception:
        pass

    world.set_weather(w)
    print(f"Foggy preset applied ({variant}).")


In [20]:
def cool_down_camera_bp(cam_bp):
    # If present in your build; safe to ignore if attribute missing
    for k, v in [
        ("exposure_mode", "manual"),
        ("exposure_compensation", "-0.3"),
        ("white_balance_temp", "4500"),   # cooler (default ~6500)
        ("motion_blur_intensity", "0.0"),
    ]:
        if cam_bp.has_attribute(k):
            cam_bp.set_attribute(k, v)


In [23]:
import carla

def set_weather_rain(world, variant="day"):
    """
    Realistic rain look:
      - high precipitation + wetness
      - heavy clouds
      - some fog (reduced visibility)
      - lower sun angle for flatter lighting
    variant: "day" or "night"
    """
    w = world.get_weather()
    w.cloudiness = 85.0
    w.precipitation = 90.0            # rain intensity (visual rain)
    w.precipitation_deposits = 80.0   # puddles/wet accumulation
    w.wetness = 95.0                   # reflective wet roads
    w.wind_intensity = 50.0

    w.fog_density = 25.0               # moderate visibility loss
    w.fog_distance = 60.0
    w.fog_falloff = 1.2

    w.sun_azimuth_angle = 45.0
    w.sun_altitude_angle = 15.0 if variant == "day" else -5.0

    # Optional scattering tweaks (ignored if not supported by your build)
    for k, v in [
        ("scattering_intensity", 0.4),
        ("mie_scattering_scale", 0.02),
        ("rayleigh_scattering_scale", 0.3),
    ]:
        try:
            setattr(w, k, v)
        except Exception:
            pass

    world.set_weather(w)
    print(f"Rain preset applied ({variant}).")

# Example:
set_weather_rain(world, variant="day")     # or "night"


Rain preset applied (day).


In [13]:
env = "rain"        # <— update this before spawning cameras / saving
scene = "scene_rain_day_0001"   # e.g., use a new scene name


## 6. Intrinsic & Extrinsic Calibration Helpers (Commented Reference)
These cells contain commented reference code for computing the intrinsic matrix `K`, camera-to-ego transforms, and writing calibration JSON files.


In [ ]:
################## INTRINSIC MATRIX K


In [26]:
# import math
# import numpy as np

# def get_intrinsic_matrix(width: int, height: int, fov_deg: float):
#     f = width / (2.0 * math.tan(math.radians(fov_deg / 2.0)))
#     K = np.array([
#         [f, 0, width / 2.0],
#         [0, f, height / 2.0],
#         [0, 0, 1]
#     ])
#     return K

# W, H, HFOV = 1280, 720, 90.0
# K = get_intrinsic_matrix(W, H, HFOV)
# print("Intrinsic K:\n", K)


Intrinsic K:
 [[640.   0. 640.]
 [  0. 640. 360.]
 [  0.   0.   1.]]


In [28]:
# #### GETTING TRANSFORMATION MATRICES FROM THE CAMERA
# def transform_to_matrix(transform: carla.Transform):
#     """CARLA Transform → 4×4 homogeneous matrix"""
#     loc = transform.location
#     rot = transform.rotation

#     # rotation in degrees → radians
#     rx, ry, rz = map(math.radians, [rot.roll, rot.pitch, rot.yaw])

#     # rotation matrices (R = Rz * Ry * Rx)
#     Rz = np.array([
#         [math.cos(rz), -math.sin(rz), 0],
#         [math.sin(rz),  math.cos(rz), 0],
#         [0, 0, 1]
#     ])
#     Ry = np.array([
#         [math.cos(ry), 0, math.sin(ry)],
#         [0, 1, 0],
#         [-math.sin(ry), 0, math.cos(ry)]
#     ])
#     Rx = np.array([
#         [1, 0, 0],
#         [0, math.cos(rx), -math.sin(rx)],
#         [0, math.sin(rx),  math.cos(rx)]
#     ])
#     R = Rz @ Ry @ Rx
#     T = np.eye(4)
#     T[:3, :3] = R
#     T[:3, 3] = [loc.x, loc.y, loc.z]
#     return T


In [30]:
# # get transform matrices
# ego_tf = transform_to_matrix(ego.get_transform())       # ego → world
# cam_tf = transform_to_matrix(cam.get_transform())       # camera → world

# # cam→ego = (ego→world)^(-1) * (cam→world)
# cam2ego = np.linalg.inv(ego_tf) @ cam_tf

# print("Ego→world:\n", ego_tf)
# print("Cam→ego:\n", cam2ego)


Ego→world:
 [[-6.21981103e-01  7.83028713e-01  2.35415301e-03 -5.38896217e+01]
 [-7.82995777e-01 -6.21920301e-01 -1.15217898e-02 -7.93825626e+00]
 [-7.55779665e-03 -9.00962737e-03  9.99930851e-01 -2.61077867e-03]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
Cam→ego:
 [[ 1.20212192e-07 -1.00000000e+00 -1.92135846e-09 -2.27511377e-02]
 [ 1.00000000e+00  1.20212192e-07 -3.17341008e-08  5.72872236e-01]
 [ 3.17341010e-08 -1.92135464e-09  1.00000000e+00  1.51039591e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]


In [24]:
# # --------- Config (edit these 3 only) ---------
# W, H = 1280, 720          # image size
# HFOV_DEG = 90.0           # horizontal FOV in degrees
# CAM_RIG = {
#     "CAM_FRONT":       dict(x=1.6,  y=0.0,  z=1.5, yaw=0),
#     "CAM_FRONT_RIGHT": dict(x=1.4,  y=0.4,  z=1.5, yaw=45),
#     "CAM_FRONT_LEFT":  dict(x=1.4,  y=-0.4, z=1.5, yaw=-45),
#     "CAM_BACK":        dict(x=-1.5, y=0.0,  z=1.5, yaw=180),
#     "CAM_LEFT":        dict(x=0.0,  y=-0.6, z=1.5, yaw=-90),
#     "CAM_RIGHT":       dict(x=0.0,  y=0.6,  z=1.5, yaw=90),
# }
# # ---------------------------------------------

# import math, numpy as np, json
# import carla

# # --- Intrinsics (pinhole) from width/height/FOV
# def get_intrinsic_matrix(width:int, height:int, fov_deg:float) -> np.ndarray:
#     f = width / (2.0 * math.tan(math.radians(fov_deg * 0.5)))  # fx = fy for square pixels
#     K = np.array([[f, 0, width/2.0],
#                   [0, f, height/2.0],
#                   [0, 0, 1]], dtype=float)
#     return K

# K = get_intrinsic_matrix(W, H, HFOV_DEG)

# # --- CARLA Transform -> 4x4 homogeneous
# def transform_to_matrix(tf: carla.Transform) -> np.ndarray:
#     loc = tf.location
#     rot = tf.rotation
#     rx, ry, rz = map(math.radians, [rot.roll, rot.pitch, rot.yaw])
#     cx, sx = math.cos(rx), math.sin(rx)
#     cy, sy = math.cos(ry), math.sin(ry)
#     cz, sz = math.cos(rz), math.sin(rz)
#     # CARLA uses yaw(Z) -> pitch(Y) -> roll(X)
#     Rz = np.array([[cz, -sz, 0],[sz, cz, 0],[0, 0, 1]])
#     Ry = np.array([[cy, 0, sy],[0, 1, 0],[-sy, 0, cy]])
#     Rx = np.array([[1, 0, 0],[0, cx, -sx],[0, sx, cx]])
#     R = Rz @ Ry @ Rx
#     T = np.eye(4)
#     T[:3,:3] = R
#     T[:3, 3] = [loc.x, loc.y, loc.z]
#     return T

# # --- spawn cameras with your rig & collect cam->ego
# cam_bp = bp_lib.find('sensor.camera.rgb')
# cam_bp.set_attribute('image_size_x', str(W))
# cam_bp.set_attribute('image_size_y', str(H))
# cam_bp.set_attribute('fov', str(HFOV_DEG))

# cams = {}
# cam2ego_mats = {}

# for name, spec in CAM_RIG.items():
#     tf = carla.Transform(
#         carla.Location(x=spec['x'], y=spec['y'], z=spec['z']),
#         carla.Rotation(pitch=0.0, roll=0.0, yaw=spec['yaw'])
#     )
#     cam = world.spawn_actor(cam_bp, tf, attach_to=ego)
#     cams[name] = cam

# # Compute cam->ego once (from current mounts)
# ego_T_world = transform_to_matrix(ego.get_transform())    # ego -> world
# ego_world_inv = np.linalg.inv(ego_T_world)

# for name, cam in cams.items():
#     cam_T_world = transform_to_matrix(cam.get_transform()) # cam -> world
#     cam_T_ego   = ego_world_inv @ cam_T_world              # cam -> ego
#     cam2ego_mats[name] = cam_T_ego

# # --- Example: print K and one extrinsic
# print("K =\n", K)
# print("cam2ego['CAM_FRONT'] =\n", cam2ego_mats["CAM_FRONT"])

# # --- Helper to log ego->world per frame (call inside your tick loop)
# def get_ego2world_now() -> np.ndarray:
#     return transform_to_matrix(ego.get_transform())

# # --- (Optional) write calibration JSON you can reuse across runs
# calib = {
#     "image_size": [W, H],
#     "fov_deg": HFOV_DEG,
#     "K": K.tolist(),
#     "cam2ego": {name: M.tolist() for name, M in cam2ego_mats.items()}
# }
# with open("calib_6cam.json", "w") as f:
#     json.dump(calib, f, indent=2)
# print("Wrote calib_6cam.json")


K =
 [[640.   0. 640.]
 [  0. 640. 360.]
 [  0.   0.   1.]]
cam2ego['CAM_FRONT'] =
 [[ 1.00000000e+00 -2.76778620e-18 -1.05932643e-22  1.59999819e+00]
 [-2.83787094e-18  1.00000000e+00  3.35740346e-23  2.30412196e-06]
 [-2.11811755e-22 -8.46940687e-23  1.00000000e+00  1.49999313e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
Wrote calib_6cam.json


## 7. Full Scripted Multi-Weather Data Collection Pipeline
A consolidated script-style version of data collection with weather modes and calibration saving.


In [41]:
import carla
import time
import os
import json
import numpy as np

def set_weather(world, mode):
    weather = carla.WeatherParameters.ClearNoon
    if mode == "clear":
        weather = carla.WeatherParameters.ClearNoon
    elif mode == "foggy":
        weather = carla.WeatherParameters(
            cloudiness=20.0, precipitation=0.0, fog_density=80.0, fog_distance=5.0
        )
    elif mode == "rainy":
        weather = carla.WeatherParameters(
            cloudiness=80.0, precipitation=80.0, wetness=100.0
        )
    elif mode == "night":
        weather = carla.WeatherParameters.ClearNight
    world.set_weather(weather)
    print(f"Weather set to: {mode}")

def spawn_camera(world, vehicle, transform, name, out_dir):
    bp = world.get_blueprint_library().find('sensor.camera.rgb')
    bp.set_attribute('image_size_x', '1280')
    bp.set_attribute('image_size_y', '720')
    bp.set_attribute('fov', '90')
    camera = world.spawn_actor(bp, transform, attach_to=vehicle)
    os.makedirs(out_dir, exist_ok=True)

    def save_img(image):
        filename = os.path.join(out_dir, f"{image.frame:06d}.png")
        image.save_to_disk(filename)

    camera.listen(save_img)
    return camera

def save_calibration(camera, file_path):
    """Save intrinsic + extrinsic matrices for PETRv2 converter"""
    cam_transform = camera.get_transform()
    cam_intrinsic = np.identity(3)
    fov = camera.attributes['fov']
    width = int(camera.attributes['image_size_x'])
    height = int(camera.attributes['image_size_y'])
    focal = width / (2.0 * np.tan(float(fov) * np.pi / 360.0))
    cam_intrinsic[0, 0] = cam_intrinsic[1, 1] = focal
    cam_intrinsic[0, 2] = width / 2.0
    cam_intrinsic[1, 2] = height / 2.0

    # Extrinsic (world → camera)
    extrinsic = np.array(cam_transform.get_matrix())

    calib = {"intrinsic": cam_intrinsic.tolist(), "extrinsic": extrinsic.tolist()}
    os.makedirs(os.path.dirname(file_path), exist_ok=True)
    with open(file_path, "w") as f:
        json.dump(calib, f, indent=2)

def main():
    client = carla.Client('localhost', 2000)
    client.set_timeout(10.0)
    world = client.get_world()

    vehicle_bp = world.get_blueprint_library().filter('vehicle.tesla.model3')[0]
    spawn_point = world.get_map().get_spawn_points()[0]
    vehicle = world.spawn_actor(vehicle_bp, spawn_point)

    # Define camera transforms
    cameras = {
        "cam_front": carla.Transform(carla.Location(x=1.6, y=0, z=1.5), carla.Rotation(yaw=0)),
        "cam_front_left": carla.Transform(carla.Location(x=1.4, y=-0.4, z=1.5), carla.Rotation(yaw=-45)),
        "cam_front_right": carla.Transform(carla.Location(x=1.4, y=0.4, z=1.5), carla.Rotation(yaw=45)),
        "cam_back": carla.Transform(carla.Location(x=-1.5, y=0, z=1.5), carla.Rotation(yaw=180)),
        "cam_left": carla.Transform(carla.Location(x=0, y=-0.6, z=1.5), carla.Rotation(yaw=-90)),
        "cam_right": carla.Transform(carla.Location(x=0, y=0.6, z=1.5), carla.Rotation(yaw=90))                           
        
    }

    weather_modes = ["clear", "foggy", "rainy"]
    root_dir = "carla_dataset"

    for mode in weather_modes:
        set_weather(world, mode)
        out_dir = os.path.join(root_dir, mode)
        cameras_list = []
        for name, transform in cameras.items():
            cam = spawn_camera(world, vehicle, transform, name, os.path.join(out_dir, "images", name))
            cameras_list.append((name, cam))

        # Record for a few seconds (you can adjust)
        time.sleep(10)

        # Save calibration JSONs
        for name, cam in cameras_list:
            save_calibration(cam, os.path.join(out_dir, "calib", f"{name}.json"))
            cam.stop()
            cam.destroy()

    vehicle.destroy()
    print("Data collection completed.")

#if _name_ == "_main_":
main()

Weather set to: clear
Weather set to: foggy
Weather set to: rainy
Data collection completed.
